### ISSUE TITLE
Wiki Closed

### ISSUE THREAD

**Issue by ereizas** [arthurdjn/scrape-lyricwiki#1]
When I tried retrieving the lyrics for any song (following the suggested flow in the README), I got the message: "HTTP Error 410: Gone. Failed to connect to https://lyrics.fandom.com/wiki/...". Then I checked the site and saw that the wiki is closed. Neither of the files that the page suggested downloading had enough lyric data to be useful.

**Comment by arthurdjn** [comment]
Thanks for pointing it out. The package will no longer work then, but I will leave it there.
